config/urls.py
from django.contrib import admin
from django.urls import path,include
# from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    
]

pybo/urls.py
from django.urls import path
from pybo import views

app_name = 'pybo'

urlpatterns = [
  path('',views.index, name='index'),
  path('<int:question_id>/', views.detail, name='detail'),
  path('answer/create/<int:question_id>', views.answer_create, name='answer_create'),
  path('question/create/', views.question_create, name='question_create'),
] 

pybo/models.py
from django.db import models

class Question(models.Model):
  subject = models.CharField(max_length=200) 
  content = models.TextField()
  create_date = models.DateTimeField()#입력시간 출력함수 장고쉘에서 create_date=timezone.now()로 활용

  def __str__(self):
    return self.subject

class Answer(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  content = models.TextField()
  create_date =models.DateTimeField()

pybo/forms.py
from django import forms
from pybo.models import Question

class QuestionForm(forms.ModelForm):
  class Meta:
    model = Question
    fields = ['subject', 'content']
  

pybo/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Question
from django.utils import timezone
from .forms import QuestionForm

def index(request):
  """
  pybo 목록 출력
  """
  question_list = Question.objects.order_by('-create_date')
  context = {'question_list': question_list}
  return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
  """
  pybo 목록 출력
  """
  question = Question.objects.get(id=question_id)
  context = {'question': question}
  return render(request, 'pybo/question_detail.html', context)
  
def answer_create(request, question_id):
  """  
  pybo 답변등록
  """
  question = get_object_or_404(Question, pk=question_id)
  question.answer_set.create(content=request.POST.get('content'),create_date=timezone.now())
  return redirect('pybo:detail', question_id=question.id)

def question_create(request):
  """  
  pybo 답변등록
  """
  if request.method == 'POST':
    form = QuestionForm(request.POST)
    if form.is_valid():
      question = form.save(commit=false)
      question.create_date = timezone.now()
      question.save()
      return redirect('pybo:index')

  else:
    form = QuestionForm()
  context = {'form': form}
  return render(request, 'pybo/question_form.html', context)
  

    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>

    <!-- pybo CSS -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'style.css' %}"
    />

    <title>Hello, pybo!</title>
  </head>
  <body>
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %} 
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
  </body>
</html>

templates/pybo/question_detail.html
{% extends 'base.html'%}
{% block content %}
<div class="container my-3">
  <h2 class="border-bottom py-2">{{ question.subject }}</h2>
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line;">
        {{ question.content }}
      </div>
      <div class="d-flex justify-content-end">
        <div class="badge badge-light p-2">
          {{ question.create_date }}
        </div>
      </div>
    </div>
  </div>
  
  <h5 class="border-bottom my-3 py-2">
    {{ question.answer_set.count }}개의 답변이 있습니다.
  </h5>
  
  {% for answer in question.answer_set.all %}
    <div class="card my-3">
      <div class="card-body">
        <div class="card-text" style="white-space: pre-line;">
          {{ answer.content }}
        </div>
        <div class="d-flex justify-content-end">
          <div class="badge badge-light p-2">
            {{ answer.create_date }}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

  <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
    {% csrf_token %}
    <div class="form-group">
      <textarea name="content" id="content" class="form-control" rows="10"></textarea>
    </div>
    <input type="submit" value="답변 등록" class="btn btn-primary">
  </form>
</div>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">질문등록</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %} 
{% block content %}
<div class="container my-3">
  <table class="table">
    <thead>
      <tr class="thead-dark">
        <th>번호</th>
        <th>제목</th>
        <th>작성일시</th>
      </tr>
    </thead>
    <tbody>
      {% if question_list %} {% for question in question_list %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>
          <a href="{% url 'pybo:detail' question.id %}">
            {{ question.subject }}
          </a>
        </td>
        <td>{{ question.create_date }}</td>
      </tr>
      {% endfor %} {% else %}
      <tr>
        <td colspan="3">질문이 없습니다.</td>
      </tr>
      {% endif %}
    </tbody>
  </table>
  <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">
    질문 등록하기
  </a>
</div>
{% endblock %}